spring:
  application:
    name: gymapp_rest
  datasource:
    url: jdbc:postgresql://localhost:5432/gymapp_rest
    username: costigan
    password: BillyCostigan
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

